### ISSUE TITLE
Error when trying to run jmeter

### ISSUE THREAD

**Issue by McCo0L** [f1xxxer/jmetertests#2]
Jmeter is not able to run on Azure because how Azure cointaners work you need to add a workaround you need to add:
```
IP=`hostname -i | awk '{print $1}'`

# We use environment variables to set test folder and test plan file
jmeter -n -t "/${TEST_DIR}/${TEST_FILE}" -l "/${TEST_DIR}/test-results.jtl" -R ${SERVERS} -e -o /${TEST_DIR}/report -j "/${TEST_DIR}/controller-run.log" -Djava.rmi.server.hostname=$IP
```
to controller and server script to allow it to start. Anyway after adding it controller still cannot comunicate with servers with this error:

```
Error in rconfigure() method java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
Error in rconfigure() method java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
Remote engines have been started:[]
The following remote engines have not started:
```
Any idea on this?

**Comment by f1xxxer** [comment]
Jmeter is able to run on Azure - this is something I've been using on real projects. If you're not able to connect somewhere then there might be need to have a look into networking, which might have it's differences based on the Container Instances pricing.

At the moment I see it can't connect to the localhost IP (127.0.0.1), so just based on your message it's hard to say, where's the problem. Maybe you can provide more context?

**Comment by f1xxxer** [comment]
closing this because due to lack of activity
